OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET UTF8
INFILE 'carga.csv'
INTO TABLE temporal
FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(
    NOMBRE_ELECCION,
    YEAR_ELECCION,
    PAIS, 
    REGION, 
    DEPTO, 
    MUNICIPIO, 
    PARTIDO, 
    NOMBRE_PARTIDO, 
    SEXO, 
    RAZA,
    ANALFABETOS,
    ALFABETOS, 
    SEXO2, 
    RAZA2, 
    PRIMARIA,
    NIVEL_MEDIO,
    UNIVERSITARIOS
)